//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momente.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Momente.Resources.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment löschen?.
        /// </summary>
        internal static string DeleteMomentQuestion {
            get {
                return ResourceManager.GetString("DeleteMomentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibe einen kurzen Text....
        /// </summary>
        internal static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift....
        /// </summary>
        internal static string HeadlinePlaceholder {
            get {
                return ResourceManager.GetString("HeadlinePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment speichern?.
        /// </summary>
        internal static string SaveMomentQuestion {
            get {
                return ResourceManager.GetString("SaveMomentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach....
        /// </summary>
        internal static string SearchfilterPlaceholder {
            get {
                return ResourceManager.GetString("SearchfilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisher keine Treffer bei der Suche: Weitersuchen?.
        /// </summary>
        internal static string SearchLimitReachedText {
            get {
                return ResourceManager.GetString("SearchLimitReachedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine weitere Übereinstimmung in dieser Richtung gefunden..
        /// </summary>
        internal static string SearchMsgNoMoreResults {
            get {
                return ResourceManager.GetString("SearchMsgNoMoreResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freut mich dich hier begrüßen zu dürfen.
        ///
        ///Mit dieser App kannst du Momente und Eindrücke sammeln.
        ///
        ///Wenn du dann mal einen schlechten Tag hast, kannst du in diese Momente zurück eintauchen und Energie aus ihnen schöpfen.
        ///
        ///Ich wünsche dir viele bunte Momente!.
        /// </summary>
        internal static string WelcomeMomentDescription {
            get {
                return ResourceManager.GetString("WelcomeMomentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen!.
        /// </summary>
        internal static string WelcomeMomentHeadline {
            get {
                return ResourceManager.GetString("WelcomeMomentHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
